/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_pbo;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ndogs
 */
public class Form_update_soal extends javax.swing.JFrame {

    /**
     * Creates new form update_soal
     */
    public Form_update_soal() {
        initComponents();
        tampil_soal();
    }

    void tampil_soal() {
        Object[] header = {"no", "Kategori", "Soal"};
        model_tabel = new DefaultTableModel(null, header);
        tb_soal.setModel(model_tabel);
        tb_soal.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tb_soal.getColumnModel().getColumn(0).setPreferredWidth(65);
        tb_soal.getColumnModel().getColumn(1).setPreferredWidth(100);
        tb_soal.getColumnModel().getColumn(2).setPreferredWidth(450);

        try {
            hasil = soal.getData();
            while (hasil.next()) {
                soal.setKategori(hasil.getString("kategori"));
                soal.setIsi_soal(hasil.getString("isi_soal"));
                String[] isi = {hasil.getString("id_jawaban"), soal.getKategori(), soal.getIsi_soal()};
                model_tabel.addRow(isi);
            }
        } catch (Exception e) {

        }
    }

    void clear_form() {
        txt_soal.setText("");
        txt_pil_a.setText("");
        txt_pil_b.setText("");
        txt_pil_c.setText("");
        txt_pil_d.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_soal = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cb_kategori = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_soal = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txt_pil_a = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_pil_b = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_pil_c = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_pil_d = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cb_kunci = new javax.swing.JComboBox<>();
        btn_update = new javax.swing.JButton();
        backToMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_soal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kategori", "Soal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_soal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_soalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_soal);
        if (tb_soal.getColumnModel().getColumnCount() > 0) {
            tb_soal.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel8.setText("Kategori");

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiqh", "SPI", "Quran dan Hadits" }));

        jLabel2.setText("Soal");

        txt_soal.setColumns(20);
        txt_soal.setRows(5);
        jScrollPane2.setViewportView(txt_soal);

        jLabel3.setText("Jawaban A ");

        txt_pil_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pil_aActionPerformed(evt);
            }
        });

        jLabel4.setText("Jawaban B ");

        jLabel5.setText("Jawaban C ");

        jLabel6.setText("Jawaban D ");

        txt_pil_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pil_dActionPerformed(evt);
            }
        });

        jLabel7.setText("Jawaban Benar");

        cb_kunci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan A", "Pilihan B", "Pilihan C", "Pilihan D" }));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        backToMenu.setForeground(new java.awt.Color(255, 0, 0));
        backToMenu.setText("Back");
        backToMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(14, 14, 14)
                                .addComponent(cb_kunci, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_pil_c, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_pil_d)
                                            .addComponent(txt_pil_b)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jScrollPane2)
                                            .addComponent(txt_pil_a))))))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backToMenu)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backToMenu)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pil_a, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pil_b, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pil_c, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pil_d, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cb_kunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pil_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pil_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pil_aActionPerformed

    private void txt_pil_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pil_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pil_dActionPerformed

    private void backToMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMenuMouseClicked
        // TODO add your handling code here:
        Form_menu_admin admin = new Form_menu_admin();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backToMenuMouseClicked

    private void tb_soalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_soalMouseClicked
        // TODO add your handling code here:
        int row = tb_soal.rowAtPoint(evt.getPoint());
        id_jawaban = Integer.parseInt(tb_soal.getValueAt(row, 0).toString());
        String kategori = tb_soal.getValueAt(row, 1).toString();
        try {
            hasil_soal = soal.searchByIdJawaban(id_jawaban);
            hasil_soal.next();

            jawaban.setPil_A(hasil_soal.getString("pilihan_a"));
            jawaban.setPil_B(hasil_soal.getString("pilihan_b"));
            jawaban.setPil_C(hasil_soal.getString("pilihan_c"));
            jawaban.setPil_D(hasil_soal.getString("pilihan_d"));
            jawaban.setKunci(hasil_soal.getString("kunci"));

            txt_soal.setText(hasil_soal.getString("isi_soal"));
            txt_pil_a.setText(jawaban.getPil_A());
            txt_pil_b.setText(jawaban.getPil_B());
            txt_pil_c.setText(jawaban.getPil_C());
            txt_pil_d.setText(jawaban.getPil_D());
            cb_kategori.setSelectedItem(kategori);

            if (jawaban.getKunci().equals(txt_pil_a.getText())) {
                cb_kunci.setSelectedItem("Pilihan A");
            } else if (jawaban.getKunci().equals(txt_pil_b.getText())) {
                cb_kunci.setSelectedItem("Pilihan B");
            } else if (jawaban.getKunci().equals(txt_pil_c.getText())) {
                cb_kunci.setSelectedItem("Pilihan C");
            } else if (jawaban.getKunci().equals(txt_pil_d.getText())) {
                cb_kunci.setSelectedItem("Pilihan D");
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tb_soalMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String kunci = cb_kunci.getSelectedItem().toString();

        soal.setKategori(cb_kategori.getSelectedItem().toString());
        soal.setIsi_soal(txt_soal.getText());
        jawaban.setPil_A(txt_pil_a.getText());
        jawaban.setPil_B(txt_pil_b.getText());
        jawaban.setPil_C(txt_pil_c.getText());
        jawaban.setPil_D(txt_pil_d.getText());

        switch (kunci) {
            case "Pilihan A":
                jawaban.setKunci(jawaban.getPil_A());
                break;
            case "Pilihan B":
                jawaban.setKunci(jawaban.getPil_B());
                break;
            case "Pilihan C":
                jawaban.setKunci(jawaban.getPil_C());
                break;
            case "Pilihan D":
                jawaban.setKunci(jawaban.getPil_D());
                break;
        }
        
        jawaban.update(jawaban.getPil_A(), jawaban.getPil_B(), jawaban.getPil_C(), jawaban.getPil_D(), jawaban.getKunci(), id_jawaban);
        soal.update(soal.getKategori(), soal.getIsi_soal(), id_jawaban);
        
        clear_form();
        tampil_soal();

    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_update_soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_update_soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_update_soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_update_soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_update_soal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backToMenu;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JComboBox<String> cb_kunci;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_soal;
    private javax.swing.JTextField txt_pil_a;
    private javax.swing.JTextField txt_pil_b;
    private javax.swing.JTextField txt_pil_c;
    private javax.swing.JTextField txt_pil_d;
    private javax.swing.JTextArea txt_soal;
    // End of variables declaration//GEN-END:variables

    private ResultSet hasil;
    private ResultSet hasil_soal;
    private DefaultTableModel model_tabel;
    
    private int id_jawaban;

    Crud_soal soal = new Crud_soal();
    Crud_jawaban jawaban = new Crud_jawaban();
}
