/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_pbo;

import java.sql.ResultSet;

/**
 *
 * @author ndogs
 */
public class Form_soal extends javax.swing.JFrame {

    /**
     * Creates new form soal
     */
    public Form_soal() {
        initComponents();
        tampil_soal();
    }

    int counter = 1;

    void tampil_soal() {
        label_header.setText("Soal " + counter);
        index = s_kuis.getIdSoal(counter - 1);
        hasil = soal.searchByIdSoal(index);

        try {
            hasil.next();
            id_soal = hasil.getInt("id_soal");
            kunci = hasil.getString("kunci");
            label_soal.setText(hasil.getString("isi_soal"));
            pilihan_a.setText(hasil.getString("pilihan_a"));
            pilihan_b.setText(hasil.getString("pilihan_b"));
            pilihan_c.setText(hasil.getString("pilihan_c"));
            pilihan_d.setText(hasil.getString("pilihan_d"));
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio_group = new javax.swing.ButtonGroup();
        label_header = new javax.swing.JLabel();
        label_soal = new javax.swing.JLabel();
        pilihan_a = new javax.swing.JRadioButton();
        pilihan_b = new javax.swing.JRadioButton();
        pilihan_c = new javax.swing.JRadioButton();
        pilihan_d = new javax.swing.JRadioButton();
        btn_next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_header.setFont(new java.awt.Font("8-bit pusab", 1, 24)); // NOI18N
        label_header.setText("Soal");

        label_soal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_soal.setText("Lorem Ipsum sit dolor amet consectetur alit ");
        label_soal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        radio_group.add(pilihan_a);
        pilihan_a.setText("pilihan a");

        radio_group.add(pilihan_b);
        pilihan_b.setText("pilihan b");
        pilihan_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan_bActionPerformed(evt);
            }
        });

        radio_group.add(pilihan_c);
        pilihan_c.setText("pilihan c");
        pilihan_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihan_cActionPerformed(evt);
            }
        });

        radio_group.add(pilihan_d);
        pilihan_d.setText("pilihan d");

        btn_next.setText("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilihan_a)
                                    .addComponent(pilihan_b)
                                    .addComponent(pilihan_c)
                                    .addComponent(pilihan_d)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(label_header)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(label_soal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_soal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(pilihan_a)
                .addGap(18, 18, 18)
                .addComponent(pilihan_b)
                .addGap(18, 18, 18)
                .addComponent(pilihan_c)
                .addGap(18, 18, 18)
                .addComponent(pilihan_d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pilihan_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihan_bActionPerformed

    private void pilihan_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihan_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihan_cActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        dispose();
        if (counter == 1) {
            try {
                hasil = kuis.getCurrentId();
                hasil.next();
                if (hasil.getInt(1) == 0) {
                    current = 1;
                } else {
                    current = hasil.getInt(1) + 1;
                }
//                kuis.start(s_kuis.getUsername(), current);
//                System.out.println(current);
            } catch (Exception e) {

            }

        }

        if (pilihan_a.isSelected()) {
            jawaban_player = pilihan_a.getText();
        } else if (pilihan_b.isSelected()) {
            jawaban_player = pilihan_b.getText();
        } else if (pilihan_c.isSelected()) {
            jawaban_player = pilihan_c.getText();
        } else if (pilihan_d.isSelected()) {
            jawaban_player = pilihan_d.getText();
        }

        counter++;
//        System.out.println(counter);

        kuis.setJawaban(jawaban_player);
        if (s_kuis.getStatus() == null) {
            s_kuis.setStatus("PLAYING");
            kuis.setId_kuis(current);
            if (jawaban_player.equals(kunci)) {
                kuis.setJawaban("BENAR");
                s_kuis.setSkor(s_kuis.getSkor() + 10);
            } else {
                kuis.setJawaban("SALAH");
            }

            kuis.simpan(kuis.getId_kuis(), id_soal, kuis.getJawaban());
            this.setVisible(true);
            tampil_soal();
        } else {
            if (jawaban_player.equals(kunci)) {
                kuis.setJawaban("BENAR");
                s_kuis.setSkor(s_kuis.getSkor() + 10);
            } else {
                kuis.setJawaban("SALAH");
            }

            kuis.simpan(kuis.getId_kuis(), id_soal, kuis.getJawaban());

            if (counter == 11) {
                s_kuis.setStatus("STOP");
                kuis.stop(s_kuis.getSkor(), current);
                new Form_display_score().setVisible(true);
                this.setVisible(false);
            } else {
                this.setVisible(true);
                tampil_soal();
            }

        }


    }//GEN-LAST:event_btn_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_soal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.JLabel label_header;
    private javax.swing.JLabel label_soal;
    private javax.swing.JRadioButton pilihan_a;
    private javax.swing.JRadioButton pilihan_b;
    private javax.swing.JRadioButton pilihan_c;
    private javax.swing.JRadioButton pilihan_d;
    private javax.swing.ButtonGroup radio_group;
    // End of variables declaration//GEN-END:variables

    Crud_soal soal = new Crud_soal();
    Crud_kuis kuis = new Crud_kuis();
    kuis_session s_kuis = new kuis_session();
    ResultSet hasil;

    private int id_soal, id_kuis, current, index;
    private String kunci;
    private String jawaban_player;
}
